#
# Tento soubor obsahuje konfigurační nastavení pro tvůj web
#

# Název tvého webu (zobrazeno v záhlaví)
name: Reverie

# Jméno autora
author: Andrea Mihalčíková

# Krátký popis (zobrazeno v záhlaví)
description: Elegantní téma Jekyll

# URL tvého avataru nebo profilové fotky (můžeš použít GitHub profilovou fotku)
avatar: /images/reverie.png

#
# Níže uvedená nastavení jsou volitelná
#

# Odkazy pro ikony v zápatí
footer-links:
  email: tvoje.email@domena.com
  github: amihalcikova
  twitter: amihalcikova
  linkedin: tvoje-profilova-url

# Komentáře - vlož Disqus shortname, pokud chceš aktivovat komentáře
disqus: 

# Google Analytics - vlož svůj kód UA nebo GA4 pro sledování návštěvnosti
google_analytics: 

# URL tvé stránky
url: https://amihalcikova.github.io
enforce_ssl: https://amihalcikova.github.io

# Baseurl ponech prázdné, protože používáš hlavní repozitář
baseurl: ""

#
# Níže uvedená nastavení nemusíš měnit
#

permalink: /:title/

# Jekyll 3 nyní podporuje pouze Kramdown pro Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Nastavení Sass složky
sass:
  style: :expanded

# Používané pluginy
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

include: ['_pages']

# Nastavení stránkování
paginate: 6
paginate_path: /page:num/

# Soubory, které budou vyloučeny z finálního sestavení
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME


